package common

object MsgTypes {
    const val AGENT_REGISTER = "AGENT_REGISTER"
    const val AGENT_REGISTER_OK = "AGENT_REGISTER_OK"
    const val AGENT_REGISTER_ERR = "AGENT_REGISTER_ERR"
    const val TUNNEL_CREATE = "TUNNEL_CREATE"
    const val TUNNEL_CREATE_ERR = "TUNNEL_CREATE_ERR"
    const val CLIENT_TUNNEL_OPEN = "CLIENT_TUNNEL_OPEN"
    const val CLIENT_TUNNEL_OK = "CLIENT_TUNNEL_OK"
    const val CLIENT_TUNNEL_ERR = "CLIENT_TUNNEL_ERR"
    const val AGENT_DATA_BIND = "AGENT_DATA_BIND"
    const val AGENT_DATA_BIND_OK = "AGENT_DATA_BIND_OK"
    const val AGENT_DATA_BIND_ERR = "AGENT_DATA_BIND_ERR"
}
